name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          # Isse saare configuration automatic ho jayenge
          # 'yes' command automatic 'Y' press kar degi
          yes | bubblewrap init --manifest=https://TUMHARA_RENDER_URL.onrender.com/manifest.json
          yes | bubblewrap build
